# dev 환경: react-dev(빌드된 정적 파일 서빙)로 프록시
server {
    listen 80;
    server_name _;

    location / {
        proxy_pass http://react-dev:3000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
